In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

In [2]:
mnist = input_data.read_data_sets('MNIST_data/',one_hot=True)

# 输入图片28*28
n_inputs = 28
max_time = 28
lstm_size = 100 #num of hidden layer node
n_classes = 10 #10 of the classifer
batch_size = 50 #50 of each batch 
n_batch = mnist.train.num_examples // batch_size

#input data
x = tf.placeholder(tf.float32,[None,784])

y = tf.placeholder(tf.float32,[None,10])

# variables
weights = tf.Variable(tf.truncated_normal([lstm_size,n_classes], stddev=0.1))
biases = tf.Variable(tf.constant(0.1, shape=[n_classes]))

# Network by RNN

#[time, batch, depth]
inputs = tf.reshape(x,[-1,max_time,n_inputs])
#LSTM CELL
lstm_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(lstm_size)

outputs,final_state = tf.nn.dynamic_rnn(lstm_cell, inputs, dtype = tf.float32)

#prediction
prediction = tf.nn.softmax(tf.matmul(final_state[1], weights) + biases)



#Cost function
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction,labels=y))

#Train step
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

#correct_prediction
correct_prediction = tf.equal(tf.argmax(y,1),tf.argmax(prediction,1))

#Accuracy
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

#initializer
init = tf.global_variables_initializer()

#session run time
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(6):
        for batch in range(n_batch):
            batch_xs,batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step,feed_dict = {x:batch_xs,y:batch_ys})
            
        acc = sess.run(accuracy,feed_dict = {x:mnist.test.images,y:mnist.test.labels})
        print("iter %d, Testing Accuracy:%f" %(epoch,acc))
        print(sess.run(tf.shape(outputs),feed_dict = {x:batch_xs,y:batch_ys}))
        print(sess.run(tf.shape(final_state[0]),feed_dict = {x:batch_xs,y:batch_ys}))
        print(sess.run(tf.shape(final_state[1]),feed_dict = {x:batch_xs,y:batch_ys}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
iter 0, Testing Accuracy:0.670400
[ 50  28 100]
[ 50 100]
[ 50 100]
iter 1, Testing Accuracy:0.826100
[ 50  28 100]
[ 50 100]
[ 50 100]
iter 2, Testing Accuracy:0.881200
[ 50  28 100]
[ 50 100]
[ 50 100]
iter 3, Testing Accuracy:0.898400
[ 50  28 100]
[ 50 100]
[ 50 100]
iter 4, Testing Accuracy:0.910400
[ 50  28 100]
[ 50 100]
[ 50 100]
iter 5, Testing Accuracy:0.925900
[ 50  28 100]
[ 50 100]
[ 50 100]
